added few more aliases

diff --git a/dot_bash_aliases b/dot_bash_aliases
--- a/dot_bash_aliases
+++ b/dot_bash_aliases
@@ -17,8 +17,8 @@ alias dex="sudo docker exec -i -t"
 #fin docker ip adress
 alias dip="sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}'"
 
-
-
+#ps
+alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
 #bash_functions
 function fzf-kill() {
   local pid
@@ -54,3 +54,24 @@ fstr() {
 function hg() {
     history | grep "$1";
 }
+
+# navigation
+up () {
+  local d=""
+  local limit="$1"
+
+  # Default to limit of 1
+  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
+    limit=1
+  fi
+
+  for ((i=1;i<=limit;i++)); do
+    d="../$d"
+  done
+
+  # perform cd. Show error if cd fails
+  if ! cd "$d"; then
+    echo "Couldn't go up $limit dirs.";
+  fi
+}
+
